"""Import reported fish catches from Wowhead Forever item pages (not node spawns)."""
from pathlib import Path
import argparse
import hashlib
import json
import math
import re
import time
from urllib.request import Request, urlopen
from urllib.parse import urlparse
from update_forever_wowhead import Page, ImportError

ROOT = Path(__file__).resolve().parents[1]
SOURCE = "https://www.wowhead.com/forever/"
# Classic-world fish and fishing ingredients; metadata comes from each item page.
ITEMS = (6291,6289,6303,6361,6308,6362,6317,6358,6359,6522,21071,21153,
         8365,4603,13754,13755,13756,13757,13758,13759,13760,13888,13889,13893,13422)

def validate_url(url, item):
    p = urlparse(url or "")
    if p.scheme != "https" or p.netloc != "www.wowhead.com" or not re.fullmatch(rf"/forever/item={item}(?:/[^/]*)?",p.path):
        raise ImportError(f"Expected Forever item {item}, got {url!r}")

def parse_page(html, item):
    page = Page(html)
    validate_url(page.canonical,item)
    decoder = json.JSONDecoder()
    metadata = None
    mappers = []
    for script in page.scripts:
        for m in re.finditer(r"WH\.Gatherer\.addData\(3,\s*16,\s*",script):
            data = decoder.raw_decode(script[m.end():])[0]
            if str(item) in data:
                metadata = data[str(item)]
        for m in re.finditer(r"\b(?:var\s+)?g_mapperData\s*=\s*",script):
            mappers.append(decoder.raw_decode(script[m.end():])[0])
    if not metadata or not metadata.get("name_enus") or not re.fullmatch(r"[a-zA-Z0-9_]+",metadata.get("icon","")):
        raise ImportError("Missing fish item metadata")
    zone_match = re.search(r"id:\s*['\"]fished-in['\"].*?\bdata:\s*",html,re.S)
    if not zone_match: raise ImportError("Missing fished-in zone list")
    zones = decoder.raw_decode(html[zone_match.end():])[0]
    if not isinstance(zones,list): raise ImportError("Invalid fishing zones")
    zones = [{"areaID":z["id"],"name":z["name"]} for z in zones]
    if len(mappers)>1: raise ImportError("Ambiguous mapper")
    mapper = mappers[0] if mappers and isinstance(mappers[0],dict) else {}
    area_maps = {}
    for area,layers in mapper.items():
        for layer in layers:
            if type(layer.get("uiMapId"))==int and layer["uiMapId"]>0:
                area_maps[area]=layer["uiMapId"]
    # A vendor mapper is useful for area-to-map IDs, never for catch coordinates.
    if "Fishing Locations" not in html: mapper = {}
    maps = {}
    for layers in mapper.values():
        if not isinstance(layers,list): raise ImportError("Invalid mapper layers")
        for layer in layers:
            coords = layer.get("coords")
            if not isinstance(coords,list): raise ImportError("Invalid coordinates")
            if not coords: continue
            map_id = layer.get("uiMapId")
            if map_id is None and all(p==[0,0] for p in coords): continue
            if type(map_id)!=int or map_id<=0: raise ImportError("Missing UI map ID")
            points = maps.setdefault(str(map_id),set())
            for point in coords:
                if not isinstance(point,list) or len(point)!=2 or any(type(v) not in (int,float) or not math.isfinite(v) or not 0<=v<=100 for v in point):
                    raise ImportError("Invalid catch coordinates")
                points.add(tuple(round(v*10000) for v in point))
    return {"name":metadata["name_enus"],"icon":metadata["icon"],
            "zones":zones,"areaMaps":area_maps,"maps":{k:[v for p in sorted(points) for v in p] for k,points in maps.items()}}

def render(items):
    lines = ["-- Generated by tools/update_fish_wowhead.py; do not edit.",
             "-- Reported catches from Forever item pages, not guaranteed spawns or pool locations.",
             "local name, addon = ...",
             'local iconPath = "Interface\\\\AddOns\\\\" .. name .. "\\\\icons\\\\Fish\\\\"', "addon.fishDB = {"]
    # Area 4 -> UI map 1419 verified in Forever object=142142 mapper.
    # This fills zone-only catches when no fish item exposes this map's geometry.
    area_maps = {"4":1419}
    for record in items.values(): area_maps.update(record["areaMaps"])
    for item,record in sorted(items.items(),key=lambda p:int(p[0])):
        lines.append('    {itemID=%s, type="fish", id={}, name=%s, icon=iconPath..%s, maps={' % (
            item,json.dumps(record["name"]),json.dumps(record["icon"])))
        maps = dict(record["maps"])
        for zone in record["zones"]:
            map_id = area_maps.get(str(zone["areaID"]))
            if map_id: maps.setdefault(str(map_id),[])
        for map_id, coords in sorted(maps.items(),key=lambda p:int(p[0])):
            lines.append("        [%s]={%s},"%(map_id,",".join(f"{v/1000000:.6f}".rstrip("0").rstrip(".") or "0" for v in coords)))
        lines.append("    }},")
    lines.append("}")
    return "\n".join(lines)+"\n"

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--items",type=int,nargs="+")
    parser.add_argument("--offline",action="store_true")
    parser.add_argument("--refresh",action="store_true")
    parser.add_argument("--generate-only",action="store_true")
    parser.add_argument("--delay",type=float,default=2)
    args=parser.parse_args()
    state_path=ROOT/"tools/wowhead/fish.json"
    state=json.loads(state_path.read_text()) if state_path.exists() else {"schema":1,"items":{}}
    cache=ROOT/".wowhead-cache/forever"
    cache.mkdir(parents=True,exist_ok=True)
    last=0
    if not args.generate_only:
        for item in args.items or ITEMS:
            path=cache/f"fish-{item}.html"
            url=SOURCE+f"item={item}"
            if path.exists() and (args.offline or not args.refresh):
                html=path.read_text(encoding="utf-8-sig")
            else:
                if args.offline: raise ImportError(f"Missing cached fish {item}")
                time.sleep(max(0,max(1,args.delay)-(time.monotonic()-last)))
                last=time.monotonic()
                with urlopen(Request(url,headers={"User-Agent":"GatherLite-WowheadImporter/1.0"}),timeout=35) as response:
                    validate_url(response.geturl(),item)
                    html=response.read().decode("utf-8-sig")
                parse_page(html,item)
                path.write_text(html,encoding="utf-8")
            record=parse_page(html,item)
            # Preserve previously published catch positions across refreshes.
            for map_id,coords in state["items"].get(str(item),{}).get("maps",{}).items():
                fresh=record["maps"].get(map_id,[])
                pairs=set(zip(coords[::2],coords[1::2]))|set(zip(fresh[::2],fresh[1::2]))
                record["maps"][map_id]=[v for p in sorted(pairs) for v in p]
            record["source"]=url
            record["sha256"]=hashlib.sha256(html.encode()).hexdigest()
            state["items"][str(item)]=record
            print(f'{item}: {record["name"]}: {sum(len(c)//2 for c in record["maps"].values())} catches',flush=True)
    output=render(state["items"])
    (ROOT/"plugins/fishing").mkdir(exist_ok=True)
    state_path.write_text(json.dumps(state,sort_keys=True,separators=(",",":"))+"\n",encoding="utf-8")
    (ROOT/"plugins/fishing/data.lua").write_text(output,encoding="utf-8")
    print(f'Generated {len(state["items"])} fish.')

if __name__=="__main__":
    main()
